version: 0.2

phases:
  install:
    commands:
      # 1. Node.jsの依存関係をインストール
      - echo Installing Serverless Framework and dependencies...
      - npm install
      # 2. Serverless Frameworkを安定版のバージョン3系に固定してインストール
      - npm install -g serverless@3 

  build:
    commands:
      # 3. Serverless Frameworkを使ってAWSにデプロイ
      - echo Deploying via Serverless Framework...
      - sls deploy --stage dev

artifacts:
  files:
    - '**/*'