version: 0.2

env:
  variables:
    # 必須環境変数
    STAGE: "dev"
    AWS_DEFAULT_REGION: "ap-northeast-1"
    VPC_ID: "vpc-0c5c87df6f9cc2d81" # 👈 あなたのVPC ID
    
    # DB接続用ダミー変数（serverless.yml の解決に必要）
    DATABASE_USER: "myuser"
    DATABASE_PASSWORD: "mypassword123"
    DATABASE_NAME: "mydbname"


phases:
  install:
    commands:
      - echo Installing Serverless Framework and dependencies...
      - npm install
      - npm install -g serverless@3
  
  build:
    commands:
      - echo Cleaning up previous deployment artifacts...
      # 🚨 修正点 1: 不要なオプションを削除 🚨
      - serverless remove --stage ${STAGE} --region ${AWS_DEFAULT_REGION} || true

      - echo Deploying via Serverless Framework...
      # 🚨 修正点 2: 不要なオプションを削除 🚨
      - serverless deploy --stage ${STAGE} --region ${AWS_DEFAULT_REGION}

# CodePipelineへ成果物を渡す必要がないため、artifactは空
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: .