version: 0.2

phases:
  install:
    commands:
      # 1. Node.jsの依存関係をインストール
      - echo Installing Serverless Framework and dependencies...
      - npm install
      # 2. Serverless Frameworkを安定版のバージョン3系に固定してインストール
      - npm install -g serverless@3 

  build:
    commands:
      # 1. 💡 データベースマイグレーションの実行
      # プロジェクト内でマイグレーション用スクリプトが定義されていると仮定
      - echo Running database migrations...
      - npm run migrate # または npx knex migrate:latest など

      # 2. Serverless Frameworkを使ってRDSとLambdaをデプロイ
      - echo Deploying via Serverless Framework...
      - sls deploy --stage dev 
  

artifacts:
  files:
    - '**/*'