version: 0.2

env:
  variables:
    # デプロイステージを 'dev' に設定
    STAGE: "dev"
    # AWSリージョンを東京に設定
    AWS_DEFAULT_REGION: "ap-northeast-1"



phases:
  install:
    commands:
      # 1. Node.jsの依存関係をインストール
      - echo Installing Serverless Framework and dependencies...
      - npm install
      # 2. Serverless Frameworkを安定版のバージョン3系に固定してインストール
      - npm install -g serverless@3 

  build:
    commands:
      - echo Cleaning up previous deployment artifacts...
      # 一度サービスを完全に削除するコマンド（スタックとS3バケットを消す）
      - serverless remove --stage ${STAGE} --region ${AWS_DEFAULT_REGION} || true 
      - echo Deploying via Serverless Framework...
      - serverless deploy --stage ${STAGE} --region ${AWS_DEFAULT_REGION}


      # 2. Serverless Frameworkを使ってRDSとLambdaをデプロイ
      - echo Deploying via Serverless Framework...
      - sls deploy --stage dev 
  

artifacts:
  files:
    - '**/*'